const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Behaviors.EightDir,
		C3.Behaviors.bound,
		C3.Behaviors.Flash,
		C3.Behaviors.Bullet,
		C3.Behaviors.solid,
		C3.Plugins.Keyboard,
		C3.Plugins.Particles,
		C3.Plugins.Audio,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Fade,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.Sin.Acts.SetPeriod,
		C3.Plugins.System.Exps.max,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.RestartLayout
	];
};
self.C3_JsPropNameTable = [
	{Sprite: 0},
	{Sprite2: 0},
	{Sine: 0},
	{BtnPlay: 0},
	{Text: 0},
	{Mouse: 0},
	{Sprite3: 0},
	{"8Direction": 0},
	{BoundTo: 0},
	{Flash: 0},
	{Player: 0},
	{Bullet: 0},
	{LaserPlayer: 0},
	{Enemy: 0},
	{Solid: 0},
	{Meteor: 0},
	{TxtScore: 0},
	{TxtTime: 0},
	{TxtLevel: 0},
	{HeartBar: 0},
	{Keyboard: 0},
	{bg: 0},
	{BtnTryAgain: 0},
	{BtnHome: 0},
	{MuzzleFlash: 0},
	{Explosion: 0},
	{LaserEnemy: 0},
	{Audio: 0},
	{TxtFinalTime: 0},
	{TxtFinalScore: 0},
	{TxtFinalLevel: 0},
	{Sprite4: 0},
	{TxtWinScore: 0},
	{TxtWinTime: 0},
	{TxtWinLevel: 0},
	{HeartBar2: 0},
	{BtnTryAgain2: 0},
	{BtnHome2: 0},
	{Confetti: 0},
	{Confeti2: 0},
	{Fade: 0},
	{TextFont: 0},
	{Planet: 0},
	{Score: 0},
	{Level: 0},
	{Timer: 0},
	{HP: 0},
	{EnemyShootRate: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	BtnPlay: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Mouse: class extends self.IInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Player: class extends self.ISpriteInstance {},
	LaserPlayer: class extends self.ISpriteInstance {},
	Enemy: class extends self.ISpriteInstance {},
	Meteor: class extends self.ISpriteInstance {},
	TxtScore: class extends self.ITextInstance {},
	TxtTime: class extends self.ITextInstance {},
	TxtLevel: class extends self.ITextInstance {},
	HeartBar: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	bg: class extends self.ISpriteInstance {},
	BtnTryAgain: class extends self.ISpriteInstance {},
	BtnHome: class extends self.ISpriteInstance {},
	MuzzleFlash: class extends self.IParticlesInstance {},
	Explosion: class extends self.IParticlesInstance {},
	LaserEnemy: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	TxtFinalTime: class extends self.ITextInstance {},
	TxtFinalScore: class extends self.ITextInstance {},
	TxtFinalLevel: class extends self.ITextInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	TxtWinScore: class extends self.ITextInstance {},
	TxtWinTime: class extends self.ITextInstance {},
	TxtWinLevel: class extends self.ITextInstance {},
	HeartBar2: class extends self.ISpriteInstance {},
	BtnTryAgain2: class extends self.ISpriteInstance {},
	BtnHome2: class extends self.ISpriteInstance {},
	Confetti: class extends self.IParticlesInstance {},
	Confeti2: class extends self.IParticlesInstance {},
	TextFont: class extends self.ISpriteFontInstance {},
	Planet: class extends self.ISpriteInstance {}
}